#============================ STAGE: JRE 생성 ============================
FROM amazoncorretto:21-alpine3.21 AS jre-builder

RUN apk add --no-cache binutils

RUN $JAVA_HOME/bin/jlink \
    --verbose \
    --add-modules ALL-MODULE-PATH \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=zip-6 \
    --output /opt/jre-min


#============================ STAGE: alpine3.21 기반 런타임 이미지 ============================
FROM alpine:3.21

RUN addgroup -g 1000 appuser \
    && adduser -D -u 1000 -G appuser -H -s /sbin/nologin appuser

COPY --from=jre-builder /opt/jre-min /opt/jre

WORKDIR /app
COPY --chown=appuser:appuser ./build/libs/api-*.jar /app/app.jar

USER appuser:appuser

ENV JAVA_HOME=/opt/jre
ENV PATH="$JAVA_HOME/bin:${PATH}"
ENV TZ=Asia/Seoul
ENV JAVA_TOOL_OPTIONS="\
  -Duser.timezone=Asia/Seoul \
  -Djava.io.tmpdir=/tmp \
  -Djava.net.preferIPv4Stack=true"

COPY --chown=appuser:appuser --chmod=0755 ./scripts/run.sh /app/run.sh

ENTRYPOINT ["/app/run.sh"]
