management:
  server.port: 9000
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_INCLUDE:health,info,prometheus}
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
      group:
        readiness:
          show-components: always
        liveness:
          show-components: always
          include: livenessState

# Warmup 전역 설정 (모듈별 설정은 각 모듈의 yml에서 관리)
warmup:
  enabled: ${WARMUP_ENABLED:false}
  max-pool-size: ${WARMUP_WORKER_POOL_SIZE:5}
  await-duration: ${WARMUP_WORKER_AWAIT_DURATION:20s} # warmup 최대 허용 딜레이
