name: Release Label checker

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - labeled
      - unlabeled

jobs:
  check-release-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            major
            minor
            patch
