name: Release Drafter

on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: release-drafter/release-drafter@v6 # reference : https://github.com/release-drafter/release-drafter
        with:
          config-name: release-drafter.config.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
